version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: dockerfile.prod
    volumes:
      — .:/opt/go-postgres-docker-template
    command: "/opt/go-postgres-docker-template/go-postgres-docker-template"