version: '3.3'
services:
  go-postgres-docker-template:
    container_name: go-postgres-docker-template
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: on-failure
    volumes:
      - .:/opt/go-postgres-docker-template
    depends_on:
      - postgres-container
    user: "vscode"
    networks:
      - common-network
    command: sleep infinity

  postgres-container:
    image: postgres:12-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - common-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-container
    ports:
      - "5050:80"
    networks:
      - common-network
    restart: unless-stopped

volumes:
  database_postgres:

networks:
  common-network:
    driver: bridge